# Generated by Django 4.2.11 on 2024-06-06 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.TextField(choices=[('DRAFT', 'Черновик'), ('OPEN', 'Открыто'), ('CLOSED', 'Закрыто')], default='DRAFT'),
        ),
        migrations.CreateModel(
            name='FeaturedAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_lines', to='advertisements.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_lines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='favourite_by',
            field=models.ManyToManyField(blank=True, related_name='favourites', through='advertisements.FeaturedAds', to=settings.AUTH_USER_MODEL),
        ),
    ]
