# Generated by Django 4.2.13 on 2024-05-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
