# Generated by Django 4.2.11 on 2024-05-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('image', models.CharField(max_length=200, null=True)),
                ('release_date', models.CharField(max_length=10)),
                ('lte_exists', models.BooleanField()),
            ],
        ),
    ]
